version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    network_mode: "host"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

