version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    network_mode: "host"
    # ports:
    #   - 80:80
    #   - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - /home/ubuntu/ssl:/ssl/
