version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - /home/ubuntu/ssl:/ssl/
  server1:
    build: ./servers/serverA
    ports:
      - "5001:5000"
    networks:
      app_net:
        ipv4_address: 172.16.238.10
        ipv6_address: 2001:3984:3989::10

  server2:
    build: ./servers/serverB
    ports:
      - "5002:5000"

    networks:
      app_net:
        ipv4_address: 172.16.238.5
        ipv6_address: 2001:3984:3989::10


networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
        - subnet: "2001:3984:3989::/64"